### ISSUE TITLE
test code fails - rdflib 3.2.0

### ISSUE THREAD

**Issue by damirv** [RDFLib/FuXi#1]
The following code fails (in the test directory):

Traceback (most recent call last):
  File "testOWL.py", line 6, in <module>
    from FuXi.Rete import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/FuXi-1.3.production-py2.7.egg/FuXi/Rete/__init__.py", line 1, in <module>
    from Network import ReteNetwork, InferredGoal
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/FuXi-1.3.production-py2.7.egg/FuXi/Rete/Network.py", line 18, in <module>
    from Util import xcombine
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/FuXi-1.3.production-py2.7.egg/FuXi/Rete/Util.py", line 5, in <module>
    from FuXi.Rete.AlphaNode import AlphaNode        
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/FuXi-1.3.production-py2.7.egg/FuXi/Rete/AlphaNode.py", line 3, in <module>
    from RuleStore import N3Builtin
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/FuXi-1.3.production-py2.7.egg/FuXi/Rete/RuleStore.py", line 11, in <module>
    from rdflib.Graph import QuotedGraph, Graph
ImportError: No module named Graph

I saw that, when I installed this library, rdflib 3.2.0 is installed. Is this correct?

**Comment by sheon** [comment]
I am recently started to use FuXi and I had problems installing it following the instruction in FuXi website. Finally I installed it using the FuXi_master in GitHub. Now I want to run the test code but the testOWL.py  returns no module named Collection.

**Comment by gjhiggins** [comment]
Yes, Collection is required, e.g.
https://github.com/RDFLib/FuXi/blob/master/lib/Rete/Magic.py#L70.

But it is provided by RDFLib: 
```python
from rdflib.collection import Collection
```
https://rdflib.readthedocs.org/en/latest/apidocs/rdflib.html#module-rdflib.collection

Try with the latest version of RDFLib.

**Comment by gjhiggins** [comment]
Tests are all passing for Python 2.6, 2.7, 3.3, 3.4 & PyPy
