### ISSUE TITLE
FuXi==1.4.production fails on "from rdflib.sparql.parser import parse" - ImportError: cannot import name parse

### ISSUE THREAD

**Issue by ptwobrussell** [RDFLib/FuXi#4]
Hi - I'm trying to use the latest FuXi from a fresh virtualenv where I've installed rdflib and fuxi in a clean environment, and I'm getting the following error below. I've also included a couple of diagnostic python commands in case they're helpful. Perhaps this is just an issue related to my environment, but i'm not quite sure why it would be the case if I'm in a fresh environment and such a fundamental import is breaking FuXi from even starting. Any advice on what might be happening would be much appreciated.

``` bash
$ FuXi --help
Traceback (most recent call last):
  File "/Users/matthew/virtualenvs/test_fuxi/bin/FuXi", line 8, in <module>
    load_entry_point('FuXi==1.4.production', 'console_scripts', 'FuXi')()
  File "/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 318, in load_entry_point
  File "/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2221, in load_entry_point
  File "/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1954, in load
  File "/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/FuXi-1.4.production-py2.7.egg/FuXi/Rete/CommandLine.py", line 10, in <module>
    from FuXi.LP.BackwardFixpointProcedure import BackwardFixpointProcedure
  File "/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/FuXi-1.4.production-py2.7.egg/FuXi/LP/BackwardFixpointProcedure.py", line 30, in <module>
    from FuXi.SPARQL import EDBQuery, EDBQueryFromBodyIterator, ConjunctiveQueryMemoize
  File "/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/FuXi-1.4.production-py2.7.egg/FuXi/SPARQL/__init__.py", line 8, in <module>
    from FuXi.Rete.Magic import AdornedUniTerm
  File "/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/FuXi-1.4.production-py2.7.egg/FuXi/Rete/Magic.py", line 39, in <module>
    from rdflib.sparql.parser import parse
ImportError: cannot import name parse

(test_fuxi)Goblin:tmp matthew$ which FuXi
/Users/matthew/virtualenvs/test_fuxi/bin/FuXi

(test_fuxi)Goblin:tmp matthew$ python -c "import rdflib.sparql.parser as foo; print foo"
<module 'rdflib.sparql.parser' from '/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/rdflib-2.4.2-py2.7-macosx-10.6-intel.egg/rdflib/sparql/parser.pyc'>

(test_fuxi)Goblin:tmp matthew$ python -c "import rdflib.sparql.parser as foo; print str(dir(foo))"
['GraphPattern', 'Optional', 'URIRef', 'Union', 'Where', '_StackManager', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '_buildGraphPattern', '_buildQueryArgs', '_escape', '_escapeLiterals', '_findStatements', '_getStatements', '_listTypes', '_makeList', '_parseSelect', '_parseWhere', '_parser', '_resolveBase', '_resolvePrefixes', '_resolveShorthand', '_unescape', 'base64', 'doSPARQL', 're']
(test_fuxi)Goblin:tmp matthew$ python -c "import rdflib.sparql.parser as foo; print foo.__file__"
/Users/matthew/virtualenvs/test_fuxi/lib/python2.7/site-packages/rdflib-2.4.2-py2.7-macosx-10.6-intel.egg/rdflib/sparql/parser.pyc
```

**Comment by apseyed** [comment]
Hi there,

It seems like what I've experienced below was discussed in this thread and eventually solved, but, I followed the instructions at https://code.google.com/archive/p/fuxi/wikis/Installation_Testing.wiki precisely but when I attempted a test:

~/fuxi/test$ python test_example.py
Traceback (most recent call last):
  File "test_example.py", line 13, in <module>
    from FuXi.SPARQL.BackwardChainingStore import TopDownSPARQLEntailingStore
  File "/usr/local/lib/python2.7/dist-packages/FuXi/SPARQL/__init__.py", line 8, in <module>
    from FuXi.Rete.Magic import AdornedUniTerm
  File "/usr/local/lib/python2.7/dist-packages/FuXi/Rete/Magic.py", line 39, in <module>
    from rdflib.sparql.parser import parse
ImportError: cannot import name parse

Any suggestions much appreciated.

I also tried in a virtualenv:
pip install git+git://github.com/ptwobrussell/FuXi#egg=FuXi-ptwobrussell-github

but got the error:
Command /usr/local/bin/git clone -q git://github.com/ptwobrussell/FuXi /Users/blah/test/build/FuXi-ptwobrussell-github failed with error code 128 in None
Storing debug log for failure in /Users/blah/.pip/pip.log

**Comment by apseyed** [comment]
Hi there,

It seems like what I've experienced below was discussed in this thread and eventually solved, but, I followed the instructions at https://code.google.com/archive/p/fuxi/wikis/Installation_Testing.wiki precisely but when I attempted a test:

~/fuxi/test$ python test_example.py
Traceback (most recent call last):
File "test_example.py", line 13, in 
from FuXi.SPARQL.BackwardChainingStore import TopDownSPARQLEntailingStore
File "/usr/local/lib/python2.7/dist-packages/FuXi/SPARQL/init.py", line 8, in 
from FuXi.Rete.Magic import AdornedUniTerm
File "/usr/local/lib/python2.7/dist-packages/FuXi/Rete/Magic.py", line 39, in 
from rdflib.sparql.parser import parse
ImportError: cannot import name parse

More info:
$ pip freeze | grep rdflib
rdflib==2.4.2

python -c "from rdflib.sparql.parser import parse"
Traceback (most recent call last):
File "", line 1, in 
ImportError: cannot import name parse

Any suggestions much appreciated.

I also tried in a virtualenv:
pip install git+git://github.com/ptwobrussell/FuXi#egg=FuXi-ptwobrussell-github

but got the error:
Command /usr/local/bin/git clone -q git://github.com/ptwobrussell/FuXi /Users/blah/test/build/FuXi-ptwobrussell-github failed with error code 128 in None
Storing debug log for failure in /Users/blah/.pip/pip.log
